// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NioMessage.proto

package com.weibo.sdk.syncbox.type;

public final class NioMessage {
  private NioMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NioPacketOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 sort = 1;
    boolean hasSort();
    int getSort();
    
    // optional string callbackId = 2;
    boolean hasCallbackId();
    String getCallbackId();
    
    // optional int32 code = 3;
    boolean hasCode();
    int getCode();
    
    // optional string text = 4;
    boolean hasText();
    String getText();
    
    // optional string uid = 28;
    boolean hasUid();
    String getUid();
    
    // optional bytes uri = 29;
    boolean hasUri();
    com.google.protobuf.ByteString getUri();
    
    // optional bytes content = 30;
    boolean hasContent();
    com.google.protobuf.ByteString getContent();
    
    // optional bytes attache = 31;
    boolean hasAttache();
    com.google.protobuf.ByteString getAttache();
  }
  public static final class NioPacket extends
      com.google.protobuf.GeneratedMessage
      implements NioPacketOrBuilder {
    // Use NioPacket.newBuilder() to construct.
    private NioPacket(Builder builder) {
      super(builder);
    }
    private NioPacket(boolean noInit) {}
    
    private static final NioPacket defaultInstance;
    public static NioPacket getDefaultInstance() {
      return defaultInstance;
    }
    
    public NioPacket getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.weibo.sdk.syncbox.type.NioMessage.internal_static_com_weibo_sdk_utils_NioPacket_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.weibo.sdk.syncbox.type.NioMessage.internal_static_com_weibo_sdk_utils_NioPacket_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 sort = 1;
    public static final int SORT_FIELD_NUMBER = 1;
    private int sort_;
    public boolean hasSort() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getSort() {
      return sort_;
    }
    
    // optional string callbackId = 2;
    public static final int CALLBACKID_FIELD_NUMBER = 2;
    private java.lang.Object callbackId_;
    public boolean hasCallbackId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getCallbackId() {
      java.lang.Object ref = callbackId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          callbackId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCallbackIdBytes() {
      java.lang.Object ref = callbackId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        callbackId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 code = 3;
    public static final int CODE_FIELD_NUMBER = 3;
    private int code_;
    public boolean hasCode() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getCode() {
      return code_;
    }
    
    // optional string text = 4;
    public static final int TEXT_FIELD_NUMBER = 4;
    private java.lang.Object text_;
    public boolean hasText() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          text_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string uid = 28;
    public static final int UID_FIELD_NUMBER = 28;
    private java.lang.Object uid_;
    public boolean hasUid() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getUid() {
      java.lang.Object ref = uid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          uid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bytes uri = 29;
    public static final int URI_FIELD_NUMBER = 29;
    private com.google.protobuf.ByteString uri_;
    public boolean hasUri() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public com.google.protobuf.ByteString getUri() {
      return uri_;
    }
    
    // optional bytes content = 30;
    public static final int CONTENT_FIELD_NUMBER = 30;
    private com.google.protobuf.ByteString content_;
    public boolean hasContent() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }
    
    // optional bytes attache = 31;
    public static final int ATTACHE_FIELD_NUMBER = 31;
    private com.google.protobuf.ByteString attache_;
    public boolean hasAttache() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public com.google.protobuf.ByteString getAttache() {
      return attache_;
    }
    
    private void initFields() {
      sort_ = 0;
      callbackId_ = "";
      code_ = 0;
      text_ = "";
      uid_ = "";
      uri_ = com.google.protobuf.ByteString.EMPTY;
      content_ = com.google.protobuf.ByteString.EMPTY;
      attache_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasSort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, sort_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getCallbackIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, code_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getTextBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(28, getUidBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(29, uri_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(30, content_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(31, attache_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sort_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getCallbackIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, code_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getTextBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(28, getUidBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(29, uri_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(30, content_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(31, attache_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.weibo.sdk.syncbox.type.NioMessage.NioPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.weibo.sdk.syncbox.type.NioMessage.NioPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.weibo.sdk.syncbox.type.NioMessage.NioPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.weibo.sdk.syncbox.type.NioMessage.NioPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.weibo.sdk.syncbox.type.NioMessage.NioPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.weibo.sdk.syncbox.type.NioMessage.NioPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.weibo.sdk.syncbox.type.NioMessage.NioPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.weibo.sdk.syncbox.type.NioMessage.NioPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.weibo.sdk.syncbox.type.NioMessage.NioPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.weibo.sdk.syncbox.type.NioMessage.NioPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.weibo.sdk.syncbox.type.NioMessage.NioPacket prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.weibo.sdk.syncbox.type.NioMessage.NioPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.weibo.sdk.syncbox.type.NioMessage.internal_static_com_weibo_sdk_utils_NioPacket_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.weibo.sdk.syncbox.type.NioMessage.internal_static_com_weibo_sdk_utils_NioPacket_fieldAccessorTable;
      }
      
      // Construct using com.weibo.sdk.utils.NioMessage.NioPacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        sort_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        callbackId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        code_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        uid_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        uri_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        content_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        attache_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.weibo.sdk.syncbox.type.NioMessage.NioPacket.getDescriptor();
      }
      
      public com.weibo.sdk.syncbox.type.NioMessage.NioPacket getDefaultInstanceForType() {
        return com.weibo.sdk.syncbox.type.NioMessage.NioPacket.getDefaultInstance();
      }
      
      public com.weibo.sdk.syncbox.type.NioMessage.NioPacket build() {
        com.weibo.sdk.syncbox.type.NioMessage.NioPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.weibo.sdk.syncbox.type.NioMessage.NioPacket buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.weibo.sdk.syncbox.type.NioMessage.NioPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.weibo.sdk.syncbox.type.NioMessage.NioPacket buildPartial() {
        com.weibo.sdk.syncbox.type.NioMessage.NioPacket result = new com.weibo.sdk.syncbox.type.NioMessage.NioPacket(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sort_ = sort_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.callbackId_ = callbackId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.code_ = code_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.text_ = text_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.uri_ = uri_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.content_ = content_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.attache_ = attache_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.weibo.sdk.syncbox.type.NioMessage.NioPacket) {
          return mergeFrom((com.weibo.sdk.syncbox.type.NioMessage.NioPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.weibo.sdk.syncbox.type.NioMessage.NioPacket other) {
        if (other == com.weibo.sdk.syncbox.type.NioMessage.NioPacket.getDefaultInstance()) return this;
        if (other.hasSort()) {
          setSort(other.getSort());
        }
        if (other.hasCallbackId()) {
          setCallbackId(other.getCallbackId());
        }
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasText()) {
          setText(other.getText());
        }
        if (other.hasUid()) {
          setUid(other.getUid());
        }
        if (other.hasUri()) {
          setUri(other.getUri());
        }
        if (other.hasContent()) {
          setContent(other.getContent());
        }
        if (other.hasAttache()) {
          setAttache(other.getAttache());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasSort()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              sort_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              callbackId_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              code_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              text_ = input.readBytes();
              break;
            }
            case 226: {
              bitField0_ |= 0x00000010;
              uid_ = input.readBytes();
              break;
            }
            case 234: {
              bitField0_ |= 0x00000020;
              uri_ = input.readBytes();
              break;
            }
            case 242: {
              bitField0_ |= 0x00000040;
              content_ = input.readBytes();
              break;
            }
            case 250: {
              bitField0_ |= 0x00000080;
              attache_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 sort = 1;
      private int sort_ ;
      public boolean hasSort() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getSort() {
        return sort_;
      }
      public Builder setSort(int value) {
        bitField0_ |= 0x00000001;
        sort_ = value;
        onChanged();
        return this;
      }
      public Builder clearSort() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sort_ = 0;
        onChanged();
        return this;
      }
      
      // optional string callbackId = 2;
      private java.lang.Object callbackId_ = "";
      public boolean hasCallbackId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getCallbackId() {
        java.lang.Object ref = callbackId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          callbackId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCallbackId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        callbackId_ = value;
        onChanged();
        return this;
      }
      public Builder clearCallbackId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        callbackId_ = getDefaultInstance().getCallbackId();
        onChanged();
        return this;
      }
      void setCallbackId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        callbackId_ = value;
        onChanged();
      }
      
      // optional int32 code = 3;
      private int code_ ;
      public boolean hasCode() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getCode() {
        return code_;
      }
      public Builder setCode(int value) {
        bitField0_ |= 0x00000004;
        code_ = value;
        onChanged();
        return this;
      }
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        code_ = 0;
        onChanged();
        return this;
      }
      
      // optional string text = 4;
      private java.lang.Object text_ = "";
      public boolean hasText() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setText(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        text_ = value;
        onChanged();
        return this;
      }
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000008);
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      void setText(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        text_ = value;
        onChanged();
      }
      
      // optional string uid = 28;
      private java.lang.Object uid_ = "";
      public boolean hasUid() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getUid() {
        java.lang.Object ref = uid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          uid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUid(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        uid_ = value;
        onChanged();
        return this;
      }
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000010);
        uid_ = getDefaultInstance().getUid();
        onChanged();
        return this;
      }
      void setUid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        uid_ = value;
        onChanged();
      }
      
      // optional bytes uri = 29;
      private com.google.protobuf.ByteString uri_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasUri() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public com.google.protobuf.ByteString getUri() {
        return uri_;
      }
      public Builder setUri(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        uri_ = value;
        onChanged();
        return this;
      }
      public Builder clearUri() {
        bitField0_ = (bitField0_ & ~0x00000020);
        uri_ = getDefaultInstance().getUri();
        onChanged();
        return this;
      }
      
      // optional bytes content = 30;
      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasContent() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        content_ = value;
        onChanged();
        return this;
      }
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000040);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      
      // optional bytes attache = 31;
      private com.google.protobuf.ByteString attache_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasAttache() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public com.google.protobuf.ByteString getAttache() {
        return attache_;
      }
      public Builder setAttache(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        attache_ = value;
        onChanged();
        return this;
      }
      public Builder clearAttache() {
        bitField0_ = (bitField0_ & ~0x00000080);
        attache_ = getDefaultInstance().getAttache();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.weibo.sdk.utils.NioPacket)
    }
    
    static {
      defaultInstance = new NioPacket(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.weibo.sdk.utils.NioPacket)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_weibo_sdk_utils_NioPacket_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_weibo_sdk_utils_NioPacket_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020NioMessage.proto\022\023com.weibo.sdk.utils\"" +
      "\205\001\n\tNioPacket\022\014\n\004sort\030\001 \002(\005\022\022\n\ncallbackI" +
      "d\030\002 \001(\t\022\014\n\004code\030\003 \001(\005\022\014\n\004text\030\004 \001(\t\022\013\n\003u" +
      "id\030\034 \001(\t\022\013\n\003uri\030\035 \001(\014\022\017\n\007content\030\036 \001(\014\022\017" +
      "\n\007attache\030\037 \001(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_weibo_sdk_utils_NioPacket_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_weibo_sdk_utils_NioPacket_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_weibo_sdk_utils_NioPacket_descriptor,
              new java.lang.String[] { "Sort", "CallbackId", "Code", "Text", "Uid", "Uri", "Content", "Attache", },
              com.weibo.sdk.syncbox.type.NioMessage.NioPacket.class,
              com.weibo.sdk.syncbox.type.NioMessage.NioPacket.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
